### ISSUE TITLE
Id is not defined

### ISSUE THREAD

**Issue by ghost** [weareswat/jira-github-issue-sync#22]
Hey, i got an error

TypeError: Cannot read property 'id' of undefined
    at /usr/lib/node_modules/sync-jira-github/lib/syncer.js:38:71
    at Request._callback (/usr/lib/node_modules/sync-jira-github/node_modules/jira/lib/jira.js:250:13)
    at Request.self.callback (/usr/lib/node_modules/sync-jira-github/node_modules/request/main.js:127:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/sync-jira-github/node_modules/request/main.js:767:16)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/sync-jira-github/node_modules/request/main.js:729:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by donbonifacio** [comment]
Hey @alextc001 ,
This repo isn't maintained anymore.
Please try to fix it with a PR or try a more recent fork:
https://github.com/stephanieerin/jira-github-issue-sync
